networks:
  dunodockernet:
    driver: bridge

services:
  api:
    container_name: duno-api
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - zookeeper
      - kafka
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: duno-api/Dockerfile
    networks:
      - dunodockernet
    environment:
      - STORAGE_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017
      - KAFKA_URI=kafka:9092

  gateway:
    container_name: duno-gateway
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - zookeeper
      - kafka
    ports:
      - "7000:7000"
    build:
      context: .
      dockerfile: duno-gateway/Dockerfile
    networks:
      - dunodockernet
    environment:
      - RATE_LIMIT_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017
      - KAFKA_URI=kafka:9092

  redis:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    networks:
      - dunodockernet

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.data/db:/data/db
    networks:
      - dunodockernet

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - dunodockernet

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - dunodockernet