services:
  api:
    container_name: derailed-api
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - zookeeper
      - kafka
    ports:
      - "5000:5000"
    image: "ghcr.io/derailedapp/derailed-api:master"
    environment:
      - STORAGE_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017
      - KAFKA_URI=kafka:9092
      - INSTANCE_NAME=one.derailed.docker

  gateway:
    container_name: derailed-gateway
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - zookeeper
      - kafka
    ports:
      - "7000:7000"
    image: "ghcr.io/derailedapp/derailed-gateway:master"
    environment:
      - RATE_LIMIT_URI=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017
      - KAFKA_URI=kafka:9092
      - PORT=7000

  jan:
    container_name: jan
    restart: unless-stopped
    depends_on:
      - gateway
      - api
    ports:
      - "443:443"
      - "80:80"
    image: "ghcr.io/derailedapp/january:master"
    environment:
      - SERVER_NAME=derailed.one
      - API_URL=api
      - GATEWAY_URL=gateway

  redis:
    image: eqalpha/keydb

  mongo:
    image: mongo
    volumes:
      - ./.data/db:/data/db

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    depends_on:
      - zookeeper
